---
#
# Ansible managed
#
language: python

python:
  - "3.7"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="alpine" tag="latest"
    - image="alpine" tag="edge"
    - image="debian" tag="latest"
    - image="ubuntu" tag="latest"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "ASIGeKEWVpVIbTEFLu3nRam1JYX39Ec6jMIeByyZJCFKA49MvisfKvoKZSbqkmYB83/4z94dEkgxSOPV9/yMMqqrZTVlycHmOfc8LQ24RaILD+hCxlc/PTGFdcwgRu8sAWVK3Tqa6y1fpb3DWFJdnDmhZVWucCp9381kDaRD1hRJ4fipea460xhLibPiqzzB1IGaRZDyQTeIRD1MDRBk4c5L7etVhDWACL47MM+Q5IE/ZuJnDYftF9cNxn+5W4AVlRY/56hR/IiO7D2IbxWt4JutDcG72z/ECDWVPGwA+8kW9/KX6QKd6eYH6MKSwwl/9o5SLKJoMHgH0Phbgqiczc3/BKAEOK1yknuS5O5YirzKwlthcSZTM0EMgIivG9SHO5qNvOdx4x3Df2O/ZuQdrmgisrSlTecP474vTL3ELZL42JrTfaD0uKusV+cPIIoQdeohvRRzuUHCbUgJcQiGDJaIN3PBhXDWfOjbkQKUsSWyjpHqp8zdw+L4HaFdWdq7t6U9WYXe7mYCmYpH42vRtqzzNQNFM6oZfEqMTkWqa0hlX5DfuvVTVgy1vFNegTGgTtSf6p8pP7YJnblM++NqW3M+lCFJRjyGEAXpCYRrStUVaU/I0MaD8lUC2gYjC67xHGEu+doeBqfEYIkM245bSTa+/29QtQ7AtvjzPPUnurI="
  email: false
