---
- name: test if jenkins_port is set correctly
  assert:
    that:
      - jenkins_port is defined
      - jenkins_port is number
      - jenkins_port | int > 0
      - jenkins_port | int < 65535
    quiet: yes

- name: test if jenkins_listen_address is set correctly
  assert:
    that:
      - jenkins_listen_address is defined
    quiet: yes
