---
# tasks file for jenkins
- name: load default variables
  include_vars:
    file: default.yml

- name: load os-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - default.yml

- name: add yum repository
  yum_repository:
    name: jenkins
    description: Jenkins repository
    baseurl: "{{ jenkins_yum_repository_baseurl }}"
  when:
    - ansible_pkg_mgr == "dnf" or ansible_pkg_mgr == "yum"

- name: import rpm key
  rpm_key:
    key: "{{ jenkins_rpm_key }}"
    state: present
  when:
    - ansible_pkg_mgr == "dnf" or ansible_pkg_mgr == "yum"

- name: add apt key
  apt_key:
    url: "{{ jenkins_apt_key_url }}"
    state: present
  when:
    - ansible_pkg_mgr == "apt"

- name: add apt repository
  apt_repository:
    repo: "{{ jenkins_apt_repository_repo }}"
    state: present
  when:
    - ansible_pkg_mgr == "apt"

- name: add zypper repository
  zypper_repository:
    name: jenkins
    repo: "{{ jenkins_zypper_repository_repo }}"
    state: present
  when:
    - ansible_pkg_mgr == "zypper"

- name: install software
  package:
    name: jenkins
    state: present

- name: start and enable software
  service:
    name: jenkins
    state: started
    enabled: yes
  when:
    - ansible_virtualization_type != "docker"
