---
- name: Prepare
  hosts: all
  gather_facts: no
  become: yes


  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.java
      _java_version:
        default: 8
        Debian: 11
      java_version: "{{ _java_version[ansible_distribution] | default(_java_version['default']) }}"
    - role: robertdebock.locale
    - role: robertdebock.core_dependencies
