---
- name: Prepare
  hosts: all
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.java
      java_version: 8
    - role: robertdebock.locale
    - role: robertdebock.core_dependencies
