---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: check if connection still works
      ping:
    - name: check web ui
      uri:
        url: "http://localhost:8080/login"
        return_content: yes
      register: jenkins_check_web_ui
      failed_when:
        - "'Jenkins' not in jenkins_check_web_ui.content"
